### ISSUE TITLE
The "configure" button is missing in the Modal content

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/ps_faviconnotificationbo#1]
Hi,

**Steps to reproduce the issue:** 
1- Navigate to the Module Catalog page
2- Click on the "Upload a module" button 
3- Drop the ps_faviconnotificationbo module
4- It will be installed successfully => Modal content is displayed but the configure button is missing.
![image](https://user-images.githubusercontent.com/16067358/45504005-e928ca80-b788-11e8-89fa-499d113d3d7c.png)
It should be like this 
![image](https://user-images.githubusercontent.com/16067358/45504030-f9d94080-b788-11e8-86d6-a58599c58a41.png)

Thanks & best regards, Khouloud

**Comment by marionf** [comment]
@clementdaubeuf

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10835
